mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^shoeshop/', include("shoeshop.urls")),
]

mysite/shoeshop/urls.py
from django.conf.urls import url

from . import views

app_name = 'shoeshop'

urlpatterns = [
    url(r'^$', views.login_view, name='login_view'),
    url(r'^register$', views.register, name='register'),
    url(r'^products$', views.products, name='products'),
    url(r'^cart$', views.cart, name='cart'),
    url(r'^logout_view$', views.logout_view, name='logout_view'),
]

mysite/shoeshop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class User(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL)
	phone =  models.CharField(max_length=120)
	address = models.CharField(max_length=120)

class Product(models.Model):
	name = models.CharField(max_length=200)
	price = models.FloatField(default=0)
	size = models.FloatField()
	colour = models.CharField(max_length=200)

class CartItem(models.Model):
	cart = models.ForeignKey('Cart', null=True, blank=True)
	product = models.ForeignKey(Product)
	quantity = models.IntegerField(default=1)

class Cart(models.Model):
	total = models.DecimalField(max_digits=100, decimal_places=2,

class Order(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
	order_id = models.CharField(max_length=120, default='ABC', unique=True)
	cart = models.ForeignKey(Cart)

#@receiver(post_save, sender=User)
#def save_user_profile(sender, instance, **kwargs):
#instance.profile.save()

mysite/shoeshop/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.template import RequestContext, loader
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from .models import Profile, Product, Cart
from rest_framework import viewsets
from .serializers import ProfileSerializer, ProductSerializer, CartSerializer

class ProfileViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Profile.objects.all()
    serializer_class = ProfileSerializer


class ProductViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

class CartViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Cart.objects.all()
    serializer_class = CartSerializer

def login_view(request):
	context = {}

	if(request.method == 'POST'):
		u = request.POST.get('username')
		p = request.POST.get('password')

		if(u is "" or p is ""):
			context['error'] = "Error! Please enter a value in each field."
		else:
			user = authenticate(username=u, password=p)
			if user is not None:
				login(request, user)
				request.session['username'] = u
				return HttpResponseRedirect('/shoeshop/products')
			else:
				context['error'] = "Error! Invalid login."

	return render(request, "shoeshop/login_view.html", context)

def logout_view(request):
	logout(request)
	request.session.flush()
	return HttpResponseRedirect('/shoeshop')

def register(request):
	context = {}

	if(request.method == 'POST'):
		f = request.POST['fName']
		l = request.POST['lName']
		e = request.POST['email']
		u = request.POST['username']
		ph = request.POST['phone']
		a = request.POST['address']
		p = request.POST['password']
		cp = request.POST['confirmPassword']

		if(f is "" or l is "" or e is "" or u is "" or ph is "" or a is "" or p is "" or cp is ""):
			context['error'] = "Error! Please enter a value in each field."
		elif(p != cp):
			context['error'] = "Error! Password do not match."
		else:
			Users = User.objects.all()
			for user in Users:
				if(user.email==e):
					context['error'] = "Error! Email address already exists."
				else:
					u = User.objects.create_user(first_name=f, last_name=l, email=e, username=u, password=p)
					u.profile.phone = ph
					u.profile.address = a
					u.save()
					return HttpResponseRedirect('/shoeshop')

	return render(request, 'shoeshop/register.html', context)

def products(request):
	products = Product.objects.all()

	if 'username' in request.session:
		username = request.session['username']
		user = User.objects.get(username=username)

		if 'add' in request.GET:
			product = request.GET['add']
			product_obj = Product.objects.get(pk=product)
			cart = Cart(user.id,product_obj.id,1,100.0)
			cart.save()


	return render(request, "shoeshop/products.html", {'Products':products})

def cart(request):
	context = {}

	if 'username' in request.session:
		username = request.session['username']
		user_obj = User.objects.get(username=username)

		cart = Cart.objects.get(user_id=user_obj)
		for cart_obj in cart:
			product = cart_obj.product
			context['Cart'] = product

	#cart = user.cart
	#cart_obj = Cart.objects.get[pk=username]
	#email = request.session['email_address']
	#user = User.objects.get(pk=email)
	#cart = user.cart.objects.all()

	#if 'remove' in request.GET:
		#product = request.GET['remove']
		#product_obj = Product.objects.get(pk=product)
		#Cart.objects.filter(cartproduct=product_obj).delete()

	return render(request, "shoeshop/cart.html", context)


'''
send_mail('Password reminder',
		  'Your password is...',
		  'app_email@server.com',
		  ['user1@gmail.com','user2@gmail.com'],
		  fail_silently=False)'''

mysite/shoeshop/templates/shoeshop/cart.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Shoe Shop</title>
	
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" >
</head>
<body>
	<div class="container">
		<div class = "jumbotron">
			<h1>Cart</h1>
			<h2><a href="{% url 'shoeshop:products' %}">View Products</a></h2>
			<h2><a href="{% url 'shoeshop:logout_view' %}">Logout</a></h2>
		</div>
		<div class="col-md-4 col-sm-6 col-xm-12">
			<table>
			<tr>
		    	<th>Product Name</th>
		    	<th>Product Price</th>
		    	<th>Product Size</th>
		    	<th>Product Colour</th>
		    	<th>Product Quantity</th>
		    </tr>
			{% for c in Cart %}
			<tr>
				<td>{{c.product.name}}</td>
			    <td>{{c.product.price}}</td>
			    <td>{{c.product.size}}</td>
			    <td>{{c.product.colour}}</td>
			    <td>{{c.product.quantity}}</td>
			    <td>[<a href="?remove={{c.product_id}}">Remove from Cart</a>]</td>
			</tr>
			{% endfor %}
		</div>
	</div>
</body>
</html>

mysite/shoeshop/templates/shoeshop/login_view.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Shoe Shop</title>
	
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" >

	<style>
	h1 {
		padding-bottom: 0em;
		margin-bottom: 0em;
	}
	table {
		padding-top: 0em;
		margin-top: 0em;
	}
	</style>
</head>
<body>
	<div class="container">
		<div class="jumbotron">
			<h1>Login</h1>
   			<b style="color:#FF0000";>{{error}}</b>
		   	<!--{% if loggedin %}
		   		<h2>You are logged in.</h2>
		   		<h3>Please <a href="{% url 'shoeshop:products' %}">click here</a> to continue.</h3>-->
		</div>
	</div>
		   	<!--{% else %}-->
	   		<table>
		   		<form method='POST'>
		   		{% csrf_token %}
		   		<tr>
		   			<td><label>Username:</label>
		   			<td><input type='text' maxlength='255' name='username'></input></td>
		   		</tr>
		   		<br>
		   		<tr>
		   			<td><label>Password:</label>
		   			<td><input type='text' maxlength='50' name='password'></input></td>
		   		</tr>
		   		<br>
		   		<tr>
		   			<td></td>
		   			<td><input type='submit' value='Login'></input></td>
		   		</tr>
		   		</form>
		   	</table>
		   	<h3>Sign up <a href="{% url 'shoeshop:register' %}">here</a></h3>
			<!--{% endif %}-->
</body>
</html>

mysite/shoeshop/templates/shoeshop/logout_view.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Shoe Shop</title>

	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" >
</head>
<body>
	<div class="container">
		<div class="jumbotron">
			<h1>You have been logged out.</h1>
			<h2>Please <a href="/shoeshop">click here</a> to refresh the screen.</h2>
		</div>
	</div>
</body>
</html>

mysite/shoeshop/templates/shoeshop/products.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Shoe Shop</title>
	
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" >
</head>
<body>
	<div class="container">
		<div class = "jumbotron">
			<h1>Products</h1>
			<h2><a href="{% url 'shoeshop:cart' %}">View Cart</a></h2>
			<h2><a href="{% url 'shoeshop:logout_view' %}">Logout</a></h2>		
		</div>
		<div class="col-md-4 col-sm-6 col-xm-12">
			<table>
			<tr>
		    	<th>Product Name</th>
		    	<th>Product Price</th>
		    	<th>Product Size</th>
		    	<th>Product Colour</th>
		    	<th>Product Quantity</th>
		    </tr>
			{% for product in Products %}
			<tr>
			    <td>{{product.name}}</td>
			    <td>{{product.price}}</td>
			    <td>{{product.size}}</td>
			    <td>{{product.colour}}</td>
			    <td>{{product.quantity}}</td>
			    <td>[<a href="?add={{product.id}}">Add to Cart</a>]</td>
			</tr>
			{% endfor %}
		</div>
	</div>
</body>
</html>

mysite/shoeshop/templates/shoeshop/register.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Shoe Shop</title>

	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" >

	<style>
	h1 {
		padding-bottom: 0em;
		margin-bottom: 0em;
	}
	table {
		padding-top: 0em;
		margin-top: 0em;
	}
	</style>
</head>
<body>
	<div class="container">
		<div class="jumbotron">
			<h1>Register</h1>
			<b style="color:#FF0000";>{{error}}</b>
			<table>
				<form method='POST'>
				{% csrf_token %}
				<tr>
					<td><label>First Name:</label>
					<td><input type='text' name='fName'></input></td>
				</tr>
				<br>
				<tr>
					<td><label>Last Name:</label>
					<td><input type='text' name='lName'></input></td>
				</tr>
				<br>
				<tr>
					<td><label>Email Address:</label>
					<td><input type='text' name='email'></input></td>
				</tr>
				<br>
				<tr>
					<td><label>Phone Number:</label>
					<td><input type='text' name='phone'></input></td>
				</tr>
				<br>
				<tr>
					<td><label>Address:</label>
					<td><input type='text' name='address'></input></td>
				</tr>
				<br>
				<tr>
					<td><label>Username:</label>
					<td><input type='text' name='username'></input></td>
				</tr>
				<br>
				<tr>
					<td><label>Password:</label>
					<td><input type='text' name='password'></input></td>
				</tr>
				<br>
				<tr>
					<td><label>Confirm Password:</label>
					<td><input type='text' name='confirmPassword'></input></td>
				</tr>
				<br>
				<tr>
					<td></td>
					<td><input type='submit' value='Sign up'></input></td>
				</tr>
				</form>
			</table>
		</div>
	</div>
</body>
</html>